# Generated by Django 4.0.3 on 2022-03-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivreApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_picture',
            field=models.ImageField(blank=True, default='img/Default_Image.png', null=True, upload_to='img/'),
        ),
    ]
