# Generated by Django 4.0.3 on 2022-03-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivreApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_finished',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_finished',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
