# Generated by Django 4.0.3 on 2022-03-09 13:17

import LivreApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivreApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to=LivreApi.models.upload_to),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=10, null=True),
        ),
    ]
