# Generated by Django 4.0.3 on 2022-03-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivreApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
