# Generated by Django 4.0.3 on 2022-03-14 18:17

import LivreApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivreApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='book/default-book.png', null=True, upload_to=LivreApi.models.upload_to),
        ),
    ]
