# Generated by Django 4.0.3 on 2022-03-07 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LivreApi', '0002_category_cat_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_picture',
        ),
    ]
