# Generated by Django 4.0.3 on 2022-03-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LivreApi', '0002_book_image_alter_rate_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
