# Generated by Django 4.0.3 on 2022-03-09 13:53

import LivreApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivreApi', '0003_remove_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to=LivreApi.models.upload_to),
        ),
    ]
