# Generated by Django 4.0.3 on 2022-03-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivreApi', '0003_transaction_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('exchange', 'exchange'), ('donate', 'donate')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
