# Generated by Django 4.0.3 on 2022-03-09 14:58

import LivreApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LivreApi', '0006_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='book/default-book.png', null=True, upload_to=LivreApi.models.upload_toprofile),
        ),
    ]
